// MCGeForce.h : Include file for standard system include files,
// or project specific include files.

#pragma once

#include <iostream>
#include <gfesdk/os_defines.h>
#include <gfesdk/sdk_types.h>
#include <gfesdk/sdk_types_ipc.h>
#include <gfesdk/config.h>
#include <gfesdk/isdk.h>
#include <gfesdk/highlights/ihighlights.h>

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_decobr_mcgeforce_bindings_MCGeForceHelper */

#ifndef _Included_dev_decobr_mcgeforce_bindings_MCGeForceHelper
#define _Included_dev_decobr_mcgeforce_bindings_MCGeForceHelper
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_decobr_mcgeforce_bindings_MCGeForceHelper
	 * Method:    init
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT jint JNICALL Java_dev_decobr_mcgeforce_bindings_MCGeForceHelper_init
	(JNIEnv*, jobject, jstring);

	/*
	 * Class:     dev_decobr_mcgeforce_bindings_MCGeForceHelper
	 * Method:    setVideoHighlight
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_dev_decobr_mcgeforce_bindings_MCGeForceHelper_setVideoHighlight
	(JNIEnv*, jobject, jstring, jint, jint);

	/*
	 * Class:     dev_decobr_mcgeforce_bindings_MCGeForceHelper
	 * Method:    showHighlightsEditor
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_decobr_mcgeforce_bindings_MCGeForceHelper_showHighlightsEditor
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif